id: P010546
initial_creation_type: ocr
source_metadata:
  id: bdr:W22337
  title: རྫོགས་པ་ཆེན་པོའི་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ།
  author: ''
  volumes:
    18d7b23f45644f4bb21fb265d83a619b:
      image_group_id: I1KG11732
      title: ''
      volume_number: 1
      total_pages: 330
