id: IFEB26077
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:02:56+00:00'
last_modified: '2022-06-08T14:23:54.009464+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22337
  title: རྫོགས་པ་ཆེན་པོའི་ཁྲིད་ཡིག་ཡང་ཟབ་ཡིད་བཞིན་ནོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9AF8:
      image_group_id: I1KG11732
      title: ''
      total_pages: 330
      order: 1
      base_file: 9AF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
